CONTEXT_STATUS_PENDING = "PENDING"
CONTEXT_STATUS_PROCESSING = "PROCESSING"
CONTEXT_STATUS_COMPLETED = "COMPLETED"
CONTEXT_STATUS_FAILED = "FAILED"


CONTEXT_REPRESENTATION_DIMENSION = 256


CONTEXT_ARCHITECTURE_VERSION = (
    "context-mode-v2-gated"
)