FEATURE_STATUS_PENDING = "PENDING"
FEATURE_STATUS_PROCESSING = "PROCESSING"
FEATURE_STATUS_COMPLETED = "COMPLETED"
FEATURE_STATUS_FAILED = "FAILED"

FEATURE_QUALITY_GOOD = "GOOD"
FEATURE_QUALITY_DEGRADED = "DEGRADED"
FEATURE_QUALITY_UNUSABLE = "UNUSABLE"

TEXT_SOURCE_RAW_TEXT = "RAW_TEXT"
TEXT_SOURCE_TRANSCRIPT = "TRANSCRIPT"