"""add context inference state capability

Revision ID: 055666b17d45
Revises: 5182e3d0067d
Create Date: 2026-10-01 19:28:02.134975
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '055666b17d45'
down_revision: Union[str, None] = '5182e3d0067d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_inferences', sa.Column('state_capability', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_inferences', 'state_capability')
    # ### end Alembic commands ###
