"""add text encoder revision

Revision ID: 50cf4d439e6f
Revises: 261abac430eb
Create Date: 2026-09-26 15:48:34.702760
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '50cf4d439e6f'
down_revision: Union[str, None] = '261abac430eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_features', sa.Column('encoder_revision', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_features', 'encoder_revision')
    # ### end Alembic commands ###
