"""add context inference persistence

Revision ID: 5182e3d0067d
Revises: d90f11ac06db
Create Date: 2026-09-30 17:29:24.239968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

revision: str = '5182e3d0067d'
down_revision: Union[str, None] = 'd90f11ac06db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_inferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_set_id', sa.UUID(), nullable=False),
    sa.Column('architecture_version', sa.String(length=100), nullable=False),
    sa.Column('model_revision', sa.String(length=100), nullable=False),
    sa.Column('model_artifact_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('representation_dimension', sa.Integer(), nullable=True),
    sa.Column('representation', Vector(dim=256), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('stress', sa.Float(), nullable=True),
    sa.Column('positive_mood', sa.Float(), nullable=True),
    sa.Column('social_connection', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_calibrated', sa.Boolean(), nullable=False),
    sa.Column('inference_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0.0 AND confidence_score <= 1.0)', name='ck_context_inferences_confidence_score_range'),
    sa.CheckConstraint('energy IS NULL OR (energy >= 0.0 AND energy <= 1.0)', name='ck_context_inferences_energy_range'),
    sa.CheckConstraint('positive_mood IS NULL OR (positive_mood >= 0.0 AND positive_mood <= 1.0)', name='ck_context_inferences_positive_mood_range'),
    sa.CheckConstraint('social_connection IS NULL OR (social_connection >= 0.0 AND social_connection <= 1.0)', name='ck_context_inferences_social_connection_range'),
    sa.CheckConstraint('stress IS NULL OR (stress >= 0.0 AND stress <= 1.0)', name='ck_context_inferences_stress_range'),
    sa.ForeignKeyConstraint(['feature_set_id'], ['journal_feature_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_set_id', 'architecture_version', 'model_revision', name='uq_context_inference_generation')
    )
    op.create_index(op.f('ix_context_inferences_feature_set_id'), 'context_inferences', ['feature_set_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_inferences_feature_set_id'), table_name='context_inferences')
    op.drop_table('context_inferences')
    # ### end Alembic commands ###
