"""add journal feature persistence

Revision ID: 5783d8d9c3a0
Revises: 65dccfb6923b
Create Date: 2026-09-26 11:17:13.527071
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5783d8d9c3a0'
down_revision: Union[str, None] = '65dccfb6923b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_feature_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=100), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'pipeline_version', 'source_hash', name='uq_journal_feature_generation')
    )
    op.create_index(op.f('ix_journal_feature_sets_journal_id'), 'journal_feature_sets', ['journal_id'], unique=False)
    op.create_table('audio_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_set_id', sa.UUID(), nullable=False),
    sa.Column('preprocessing_version', sa.String(length=100), nullable=False),
    sa.Column('encoder_name', sa.String(length=255), nullable=True),
    sa.Column('encoder_version', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('speech_ratio', sa.Float(), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.Column('feature_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_id'], ['journal_feature_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_features_feature_set_id'), 'audio_features', ['feature_set_id'], unique=True)
    op.create_table('text_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_set_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('preprocessing_version', sa.String(length=100), nullable=False),
    sa.Column('encoder_name', sa.String(length=255), nullable=True),
    sa.Column('encoder_version', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.Column('feature_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_id'], ['journal_feature_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_features_feature_set_id'), 'text_features', ['feature_set_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_features_feature_set_id'), table_name='text_features')
    op.drop_table('text_features')
    op.drop_index(op.f('ix_audio_features_feature_set_id'), table_name='audio_features')
    op.drop_table('audio_features')
    op.drop_index(op.f('ix_journal_feature_sets_journal_id'), table_name='journal_feature_sets')
    op.drop_table('journal_feature_sets')
    # ### end Alembic commands ###
