"""add journal audio

Revision ID: 65dccfb6923b
Revises: 0002_m1_users
Create Date: 2026-09-15 18:06:33.843239
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '65dccfb6923b'
down_revision: Union[str, None] = '0002_m1_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcription_status', sa.String(length=40), nullable=False),
    sa.Column('transcription_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_journal_audio_journal_id'), 'journal_audio', ['journal_id'], unique=True)
    op.alter_column('journal_entries', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.alter_column('journal_entries', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_journal_audio_journal_id'), table_name='journal_audio')
    op.drop_table('journal_audio')
    # ### end Alembic commands ###
